name: graduate_skills
channels:
  - conda-forge
dependencies:
  - python
  - altair
  - vl-convert-python
  - jupyterlab
  - pandas
  - anywidget
  - shiny
  - shinywidgets
  - playwright
  - pytest
  - pip

  - pip:
    - querychat
    - chatlas
    - python-dotenv
    - ibis-framework
    - pyarrow-hotfix
    - pyarrow
    - duckdb